/* ── Mock Data — used when Sanity is not configured ── */

import type { Event, Newsletter, BoardMember, Avenue } from "./types";

const mockImage = (alt: string) => ({
  _type: "image" as const,
  asset: { _ref: "image-placeholder", _type: "reference" as const },
  alt,
});

const mockFile = () => ({
  _type: "file" as const,
  asset: { _ref: "file-placeholder", _type: "reference" as const, url: "#" },
});

export const mockAvenues: Avenue[] = [
  {
    _id: "ave-1",
    _type: "avenue",
    name: "Community Service",
    slug: { _type: "slug", current: "community-service" },
    color: "#DC2626",
    description: "Serving local communities through hands-on projects and outreach programs.",
    icon: "heart",
  },
  {
    _id: "ave-2",
    _type: "avenue",
    name: "International Service",
    slug: { _type: "slug", current: "international-service" },
    color: "#2563EB",
    description: "Building connections across borders and supporting global initiatives.",
    icon: "globe",
  },
  {
    _id: "ave-3",
    _type: "avenue",
    name: "Professional Development",
    slug: { _type: "slug", current: "professional-development" },
    color: "#F59E0B",
    description: "Empowering members with skills, mentorship, and career growth opportunities.",
    icon: "briefcase",
  },
  {
    _id: "ave-4",
    _type: "avenue",
    name: "Sports & Culture",
    slug: { _type: "slug", current: "sports-culture" },
    color: "#10B981",
    description: "Celebrating diversity through sports, arts, and cultural exchange.",
    icon: "trophy",
  },
  {
    _id: "ave-5",
    _type: "avenue",
    name: "Club Service",
    slug: { _type: "slug", current: "club-service" },
    color: "#8B5CF6",
    description: "Strengthening our club through fellowship, events, and member engagement.",
    icon: "users",
  },
];

export const mockEvents: Event[] = [
  {
    _id: "evt-1",
    _type: "event",
    title: "Phoenix Rising Gala 2024",
    slug: { _type: "slug", current: "phoenix-rising-gala-2024" },
    date: "2024-12-15",
    coverImage: mockImage("Phoenix Rising Gala"),
    avenue: mockAvenues[4],
    description: "Our annual flagship gala celebrating the spirit of Rotaract. An evening of performances, awards, and fellowship that brings together members past and present. This year's theme celebrates resilience and the phoenix spirit that defines RCBW.",
    gallery: [mockImage("Gala 1"), mockImage("Gala 2"), mockImage("Gala 3")],
    isFlagship: true,
  },
  {
    _id: "evt-2",
    _type: "event",
    title: "Code for Good Hackathon",
    slug: { _type: "slug", current: "code-for-good-hackathon" },
    date: "2024-11-20",
    coverImage: mockImage("Code for Good"),
    avenue: mockAvenues[2],
    description: "A 24-hour hackathon bringing together developers, designers, and dreamers to build technology solutions for NGOs. Teams compete to create impactful tools that address real-world challenges faced by non-profit organizations in Mumbai.",
    gallery: [mockImage("Hackathon 1"), mockImage("Hackathon 2")],
    reportPDF: mockFile(),
    isFlagship: true,
  },
  {
    _id: "evt-3",
    _type: "event",
    title: "Beach Cleanup Drive",
    slug: { _type: "slug", current: "beach-cleanup-drive" },
    date: "2024-11-10",
    coverImage: mockImage("Beach Cleanup"),
    avenue: mockAvenues[0],
    description: "Join us as we clean up Juhu Beach and raise awareness about ocean conservation. Together with local communities, we've removed over 2 tonnes of waste from Mumbai's coastline this year.",
    isFlagship: false,
  },
  {
    _id: "evt-4",
    _type: "event",
    title: "Model United Nations",
    slug: { _type: "slug", current: "model-united-nations" },
    date: "2024-10-25",
    coverImage: mockImage("MUN Event"),
    avenue: mockAvenues[1],
    description: "RCBW's annual Model UN conference brings together young leaders to debate global issues, build diplomatic skills, and forge international connections. This year features committees on climate action and digital governance.",
    gallery: [mockImage("MUN 1"), mockImage("MUN 2"), mockImage("MUN 3"), mockImage("MUN 4")],
    reportPDF: mockFile(),
    isFlagship: true,
  },
  {
    _id: "evt-5",
    _type: "event",
    title: "Sports Fest — Blitz 2024",
    slug: { _type: "slug", current: "blitz-2024" },
    date: "2024-10-05",
    coverImage: mockImage("Blitz Sports Fest"),
    avenue: mockAvenues[3],
    description: "Our inter-club sports festival featuring cricket, football, basketball, and more. Teams from Rotaract clubs across Mumbai compete in a day of sportsmanship and camaraderie.",
    isFlagship: true,
  },
  {
    _id: "evt-6",
    _type: "event",
    title: "Leadership Summit",
    slug: { _type: "slug", current: "leadership-summit" },
    date: "2024-09-18",
    coverImage: mockImage("Leadership Summit"),
    avenue: mockAvenues[2],
    description: "A full-day summit featuring industry leaders, panel discussions, and workshops focused on building the next generation of leaders. Topics include entrepreneurship, social impact, and personal branding.",
    reportPDF: mockFile(),
    isFlagship: true,
  },
  {
    _id: "evt-7",
    _type: "event",
    title: "Blood Donation Camp",
    slug: { _type: "slug", current: "blood-donation-camp" },
    date: "2024-09-01",
    coverImage: mockImage("Blood Donation Camp"),
    avenue: mockAvenues[0],
    description: "Partnering with Bombay Blood Bank, we organize quarterly blood donation drives. This camp collected over 150 units of blood, potentially saving up to 450 lives.",
    isFlagship: false,
  },
  {
    _id: "evt-8",
    _type: "event",
    title: "Cultural Night — Rang",
    slug: { _type: "slug", current: "rang-cultural-night" },
    date: "2024-08-15",
    coverImage: mockImage("Cultural Night"),
    avenue: mockAvenues[3],
    description: "An evening celebrating India's Independence Day through music, dance, and art. Members showcase diverse cultural talents in this vibrant celebration of unity in diversity.",
    gallery: [mockImage("Rang 1"), mockImage("Rang 2")],
    isFlagship: true,
  },
];

export const mockNewsletters: Newsletter[] = [
  {
    _id: "nl-1",
    _type: "newsletter",
    issueNumber: 12,
    title: "The Phoenix Post — December Edition",
    date: "2024-12-01",
    coverImage: mockImage("December Newsletter"),
    pdfFile: mockFile(),
    summary: "Highlights from the Phoenix Rising Gala, upcoming winter projects, and a year-in-review retrospective celebrating RCBW's impact across all avenues of service.",
  },
  {
    _id: "nl-2",
    _type: "newsletter",
    issueNumber: 11,
    title: "The Phoenix Post — November Edition",
    date: "2024-11-01",
    coverImage: mockImage("November Newsletter"),
    pdfFile: mockFile(),
    summary: "Recap of the Code for Good Hackathon, Beach Cleanup results, member spotlights, and preview of the upcoming Phoenix Rising Gala preparations.",
  },
  {
    _id: "nl-3",
    _type: "newsletter",
    issueNumber: 10,
    title: "The Phoenix Post — October Edition",
    date: "2024-10-01",
    coverImage: mockImage("October Newsletter"),
    pdfFile: mockFile(),
    summary: "MUN conference highlights, Blitz sports fest results, new member inductions, and a feature on our International Service avenue's global partnerships.",
  },
  {
    _id: "nl-4",
    _type: "newsletter",
    issueNumber: 9,
    title: "The Phoenix Post — September Edition",
    date: "2024-09-01",
    coverImage: mockImage("September Newsletter"),
    pdfFile: mockFile(),
    summary: "Leadership Summit takeaways, Blood Donation Camp results, Rang cultural night memories, and an interview with our club president on the year ahead.",
  },
];

export const mockBoardMembers: BoardMember[] = [
  {
    _id: "bm-1",
    _type: "boardMember",
    name: "Aarav Mehta",
    role: "President",
    avenue: mockAvenues[4],
    photo: mockImage("President"),
    linkedIn: "https://linkedin.com/in/",
  },
  {
    _id: "bm-2",
    _type: "boardMember",
    name: "Priya Sharma",
    role: "Vice President",
    avenue: mockAvenues[4],
    photo: mockImage("Vice President"),
    linkedIn: "https://linkedin.com/in/",
  },
  {
    _id: "bm-3",
    _type: "boardMember",
    name: "Rohan Desai",
    role: "Secretary",
    avenue: mockAvenues[4],
    photo: mockImage("Secretary"),
    linkedIn: "https://linkedin.com/in/",
  },
  {
    _id: "bm-4",
    _type: "boardMember",
    name: "Ananya Iyer",
    role: "Community Service Director",
    avenue: mockAvenues[0],
    photo: mockImage("CS Director"),
    linkedIn: "https://linkedin.com/in/",
  },
  {
    _id: "bm-5",
    _type: "boardMember",
    name: "Kabir Patel",
    role: "International Service Director",
    avenue: mockAvenues[1],
    photo: mockImage("IS Director"),
    linkedIn: "https://linkedin.com/in/",
  },
  {
    _id: "bm-6",
    _type: "boardMember",
    name: "Diya Nair",
    role: "Professional Development Director",
    avenue: mockAvenues[2],
    photo: mockImage("PD Director"),
    linkedIn: "https://linkedin.com/in/",
  },
  {
    _id: "bm-7",
    _type: "boardMember",
    name: "Arjun Kapoor",
    role: "Sports & Culture Director",
    avenue: mockAvenues[3],
    photo: mockImage("SC Director"),
    linkedIn: "https://linkedin.com/in/",
  },
  {
    _id: "bm-8",
    _type: "boardMember",
    name: "Ishita Gupta",
    role: "Treasurer",
    avenue: mockAvenues[4],
    photo: mockImage("Treasurer"),
    linkedIn: "https://linkedin.com/in/",
  },
];
